apiVersion: v1
kind: Service
metadata:
  name: herb-city-user-service
spec:
  selector:
    app: user-service
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 31110

---

apiVersion: v1
kind: Service
metadata:
  name: herb-city-user-feedback-service
spec:
  selector:
    app: user-feedback-service 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5003
    targetPort: 5003
    nodePort: 31120

---

apiVersion: v1
kind: Service
metadata:
  name: herb-city-user-email-service
spec:
  selector:
    app: user-email-service 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5005
    targetPort: 5005
    nodePort: 31130

---

apiVersion: v1
kind: Service
metadata:
  name: herb-city-user-checkout-service
spec:
  selector:
    app: user-checkout-service 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5001
    targetPort: 5001
    nodePort: 31140

---

apiVersion: v1
kind: Service
metadata:
  name: herb-city-user-cart-service
spec:
  selector:
    app: user-cart-service 
  type: LoadBalancer
  ports:
  - protocol: TCP
    port: 5002
    targetPort: 5002
    nodePort: 31150